# This file is part of Sumak.me
# Copyright (C) 2020 Asociación SUMAK <info (at) sumakcoop (dot) org
# 
# Sumak.me is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# Sumak.me is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with Sumak.me.  If not, see <http://www.gnu.org/licenses/>.

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]

        # Uncomment to log deprecations
        #deprecation:
        #    type: stream
        #    path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        #deprecation_filter:
        #    type: filter
        #    handler: deprecation
        #    max_level: info
        #    channels: ["php"]
